/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The attachment caption.
 */
export interface AttachmentCaption {
    /**
     * Caption for the attachment, as it exists in the database.
     */
    raw?: string;
    /**
     * HTML caption for the attachment, transformed for display.
     */
    rendered?: string;
}
export interface AttachmentCaptionOpt {
    /**
     * Caption for the attachment, as it exists in the database.
     */
    raw?: string;
    /**
     * HTML caption for the attachment, transformed for display.
     */
    rendered?: string;
}
