/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Body7 {
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    /**
     * A named status for the object.
     */
    status?: Body7.StatusEnum;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * Whether or not comments are open on the object.
     */
    commentStatus?: Body7.CommentStatusEnum;
    /**
     * Whether or not the object can be pinged.
     */
    pingStatus?: Body7.PingStatusEnum;
    /**
     * Meta fields.
     */
    meta?: string;
    /**
     * The theme file to use to display the object.
     */
    template?: string;
    /**
     * Alternative text to display when attachment is not displayed.
     */
    altText?: string;
    /**
     * The attachment caption.
     */
    caption?: string;
    /**
     * The attachment description.
     */
    description?: string;
    /**
     * The ID for the associated post of the attachment.
     */
    post?: number;
}
export interface Body7Opt {
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    /**
     * A named status for the object.
     */
    status?: Body7.StatusEnum;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * Whether or not comments are open on the object.
     */
    commentStatus?: Body7.CommentStatusEnum;
    /**
     * Whether or not the object can be pinged.
     */
    pingStatus?: Body7.PingStatusEnum;
    /**
     * Meta fields.
     */
    meta?: string;
    /**
     * The theme file to use to display the object.
     */
    template?: string;
    /**
     * Alternative text to display when attachment is not displayed.
     */
    altText?: string;
    /**
     * The attachment caption.
     */
    caption?: string;
    /**
     * The attachment description.
     */
    description?: string;
    /**
     * The ID for the associated post of the attachment.
     */
    post?: number;
}
export declare namespace Body7 {
    type StatusEnum = 'publish' | 'future' | 'draft' | 'pending' | 'private';
    const StatusEnum: {
        Publish: import("./attachment").Attachment.StatusEnum;
        Future: import("./attachment").Attachment.StatusEnum;
        Draft: import("./attachment").Attachment.StatusEnum;
        Pending: import("./attachment").Attachment.StatusEnum;
        Private: import("./attachment").Attachment.StatusEnum;
    };
    type CommentStatusEnum = 'open' | 'closed';
    const CommentStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
    type PingStatusEnum = 'open' | 'closed';
    const PingStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
}
