"use strict";
/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Body;
(function (Body) {
    Body.StatusEnum = {
        Publish: 'publish',
        Future: 'future',
        Draft: 'draft',
        Pending: 'pending',
        Private: 'private'
    };
    Body.CommentStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
    Body.PingStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
    Body.FormatEnum = {
        Standard: 'standard',
        Aside: 'aside',
        Chat: 'chat',
        Gallery: 'gallery',
        Link: 'link',
        Image: 'image',
        Quote: 'quote',
        Status: 'status',
        Video: 'video',
        Audio: 'audio'
    };
})(Body = exports.Body || (exports.Body = {}));
