/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Body20 {
    /**
     * Site title.
     */
    title?: string;
    /**
     * Site tagline.
     */
    description?: string;
    /**
     * Site URL.
     */
    url?: string;
    /**
     * This address is used for admin purposes, like new user notification.
     */
    email?: string;
    /**
     * A city in the same timezone as you.
     */
    timezone?: string;
    /**
     * A date format for all date strings.
     */
    dateFormat?: string;
    /**
     * A time format for all time strings.
     */
    timeFormat?: string;
    /**
     * A day number of the week that the week should start on.
     */
    startOfWeek?: number;
    /**
     * WordPress locale code.
     */
    language?: string;
    /**
     * Convert emoticons like :-) and :-P to graphics on display.
     */
    useSmilies?: boolean;
    /**
     * Default post category.
     */
    defaultCategory?: number;
    /**
     * Default post format.
     */
    defaultPostFormat?: string;
    /**
     * Blog pages show at most.
     */
    postsPerPage?: number;
    /**
     * Allow link notifications from other blogs (pingbacks and trackbacks) on new articles.
     */
    defaultPingStatus?: Body20.DefaultPingStatusEnum;
    /**
     * Allow people to post comments on new articles.
     */
    defaultCommentStatus?: Body20.DefaultCommentStatusEnum;
}
export interface Body20Opt {
    /**
     * Site title.
     */
    title?: string;
    /**
     * Site tagline.
     */
    description?: string;
    /**
     * Site URL.
     */
    url?: string;
    /**
     * This address is used for admin purposes, like new user notification.
     */
    email?: string;
    /**
     * A city in the same timezone as you.
     */
    timezone?: string;
    /**
     * A date format for all date strings.
     */
    dateFormat?: string;
    /**
     * A time format for all time strings.
     */
    timeFormat?: string;
    /**
     * A day number of the week that the week should start on.
     */
    startOfWeek?: number;
    /**
     * WordPress locale code.
     */
    language?: string;
    /**
     * Convert emoticons like :-) and :-P to graphics on display.
     */
    useSmilies?: boolean;
    /**
     * Default post category.
     */
    defaultCategory?: number;
    /**
     * Default post format.
     */
    defaultPostFormat?: string;
    /**
     * Blog pages show at most.
     */
    postsPerPage?: number;
    /**
     * Allow link notifications from other blogs (pingbacks and trackbacks) on new articles.
     */
    defaultPingStatus?: Body20.DefaultPingStatusEnum;
    /**
     * Allow people to post comments on new articles.
     */
    defaultCommentStatus?: Body20.DefaultCommentStatusEnum;
}
export declare namespace Body20 {
    type DefaultPingStatusEnum = 'open' | 'closed';
    const DefaultPingStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
    type DefaultCommentStatusEnum = 'open' | 'closed';
    const DefaultCommentStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
}
