/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Body {
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    /**
     * A named status for the object.
     */
    status?: Body.StatusEnum;
    /**
     * A password to protect access to the content and excerpt.
     */
    password?: string;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * The content for the object.
     */
    content?: string;
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * The excerpt for the object.
     */
    excerpt?: string;
    /**
     * The ID of the featured media for the object.
     */
    featuredMedia?: number;
    /**
     * Whether or not comments are open on the object.
     */
    commentStatus?: Body.CommentStatusEnum;
    /**
     * Whether or not the object can be pinged.
     */
    pingStatus?: Body.PingStatusEnum;
    /**
     * The format for the object.
     */
    format?: Body.FormatEnum;
    /**
     * Meta fields.
     */
    meta?: string;
    /**
     * Whether or not the object should be treated as sticky.
     */
    sticky?: boolean;
    /**
     * The theme file to use to display the object.
     */
    template?: string;
    /**
     * The terms assigned to the object in the category taxonomy.
     */
    categories?: Array<string>;
    /**
     * The terms assigned to the object in the post_tag taxonomy.
     */
    tags?: Array<string>;
}
export interface BodyOpt {
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    /**
     * A named status for the object.
     */
    status?: Body.StatusEnum;
    /**
     * A password to protect access to the content and excerpt.
     */
    password?: string;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * The content for the object.
     */
    content?: string;
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * The excerpt for the object.
     */
    excerpt?: string;
    /**
     * The ID of the featured media for the object.
     */
    featuredMedia?: number;
    /**
     * Whether or not comments are open on the object.
     */
    commentStatus?: Body.CommentStatusEnum;
    /**
     * Whether or not the object can be pinged.
     */
    pingStatus?: Body.PingStatusEnum;
    /**
     * The format for the object.
     */
    format?: Body.FormatEnum;
    /**
     * Meta fields.
     */
    meta?: string;
    /**
     * Whether or not the object should be treated as sticky.
     */
    sticky?: boolean;
    /**
     * The theme file to use to display the object.
     */
    template?: string;
    /**
     * The terms assigned to the object in the category taxonomy.
     */
    categories?: Array<string>;
    /**
     * The terms assigned to the object in the post_tag taxonomy.
     */
    tags?: Array<string>;
}
export declare namespace Body {
    type StatusEnum = 'publish' | 'future' | 'draft' | 'pending' | 'private';
    const StatusEnum: {
        Publish: import("./attachment").Attachment.StatusEnum;
        Future: import("./attachment").Attachment.StatusEnum;
        Draft: import("./attachment").Attachment.StatusEnum;
        Pending: import("./attachment").Attachment.StatusEnum;
        Private: import("./attachment").Attachment.StatusEnum;
    };
    type CommentStatusEnum = 'open' | 'closed';
    const CommentStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
    type PingStatusEnum = 'open' | 'closed';
    const PingStatusEnum: {
        Open: "closed" | "open";
        Closed: "closed" | "open";
    };
    type FormatEnum = 'standard' | 'aside' | 'chat' | 'gallery' | 'link' | 'image' | 'quote' | 'status' | 'video' | 'audio';
    const FormatEnum: {
        Standard: import("./post").Post.FormatEnum;
        Aside: import("./post").Post.FormatEnum;
        Chat: import("./post").Post.FormatEnum;
        Gallery: import("./post").Post.FormatEnum;
        Link: import("./post").Post.FormatEnum;
        Image: import("./post").Post.FormatEnum;
        Quote: import("./post").Post.FormatEnum;
        Status: import("./post").Post.FormatEnum;
        Video: import("./post").Post.FormatEnum;
        Audio: import("./post").Post.FormatEnum;
    };
}
