/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Body17 {
    /**
     * Login name for the user.
     */
    username?: string;
    /**
     * Display name for the user.
     */
    name?: string;
    /**
     * First name for the user.
     */
    firstName?: string;
    /**
     * Last name for the user.
     */
    lastName?: string;
    /**
     * The email address for the user.
     */
    email?: string;
    /**
     * URL of the user.
     */
    url?: string;
    /**
     * Description of the user.
     */
    description?: string;
    /**
     * Locale for the user.
     */
    locale?: Body17.LocaleEnum;
    /**
     * The nickname for the user.
     */
    nickname?: string;
    /**
     * An alphanumeric identifier for the user.
     */
    slug?: string;
    /**
     * Roles assigned to the user.
     */
    roles?: Array<string>;
    /**
     * Password for the user (never included).
     */
    password?: string;
    /**
     * Meta fields.
     */
    meta?: string;
}
export interface Body17Opt {
    /**
     * Login name for the user.
     */
    username?: string;
    /**
     * Display name for the user.
     */
    name?: string;
    /**
     * First name for the user.
     */
    firstName?: string;
    /**
     * Last name for the user.
     */
    lastName?: string;
    /**
     * The email address for the user.
     */
    email?: string;
    /**
     * URL of the user.
     */
    url?: string;
    /**
     * Description of the user.
     */
    description?: string;
    /**
     * Locale for the user.
     */
    locale?: Body17.LocaleEnum;
    /**
     * The nickname for the user.
     */
    nickname?: string;
    /**
     * An alphanumeric identifier for the user.
     */
    slug?: string;
    /**
     * Roles assigned to the user.
     */
    roles?: Array<string>;
    /**
     * Password for the user (never included).
     */
    password?: string;
    /**
     * Meta fields.
     */
    meta?: string;
}
export declare namespace Body17 {
    type LocaleEnum = '' | 'en_US';
    const LocaleEnum: {
        Empty: import("./body15").Body15.LocaleEnum;
        EnUS: import("./body15").Body15.LocaleEnum;
    };
}
