"use strict";
/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Body20;
(function (Body20) {
    Body20.DefaultPingStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
    Body20.DefaultCommentStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
})(Body20 = exports.Body20 || (exports.Body20 = {}));
