"use strict";
/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Body15;
(function (Body15) {
    Body15.LocaleEnum = {
        Empty: '',
        EnUS: 'en_US'
    };
})(Body15 = exports.Body15 || (exports.Body15 = {}));
