"use strict";
/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Body5;
(function (Body5) {
    Body5.StatusEnum = {
        Publish: 'publish',
        Future: 'future',
        Draft: 'draft',
        Pending: 'pending',
        Private: 'private'
    };
    Body5.CommentStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
    Body5.PingStatusEnum = {
        Open: 'open',
        Closed: 'closed'
    };
})(Body5 = exports.Body5 || (exports.Body5 = {}));
