/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Category {
    /**
     * Unique identifier for the term.
     */
    id?: number;
    /**
     * Number of published posts for the term.
     */
    count?: number;
    /**
     * HTML description of the term.
     */
    description?: string;
    /**
     * URL of the term.
     */
    link?: string;
    /**
     * HTML title for the term.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the term unique to its type.
     */
    slug?: string;
    /**
     * Type attribution for the term.
     */
    taxonomy?: Category.TaxonomyEnum;
    /**
     * The parent term ID.
     */
    parent?: number;
    /**
     * Meta fields.
     */
    meta?: any;
}
export interface CategoryOpt {
    /**
     * Unique identifier for the term.
     */
    id?: number;
    /**
     * Number of published posts for the term.
     */
    count?: number;
    /**
     * HTML description of the term.
     */
    description?: string;
    /**
     * URL of the term.
     */
    link?: string;
    /**
     * HTML title for the term.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the term unique to its type.
     */
    slug?: string;
    /**
     * Type attribution for the term.
     */
    taxonomy?: Category.TaxonomyEnum;
    /**
     * The parent term ID.
     */
    parent?: number;
    /**
     * Meta fields.
     */
    meta?: any;
}
export declare namespace Category {
    type TaxonomyEnum = 'category' | 'post_tag' | 'nav_menu' | 'link_category' | 'post_format';
    const TaxonomyEnum: {
        Category: TaxonomyEnum;
        PostTag: TaxonomyEnum;
        NavMenu: TaxonomyEnum;
        LinkCategory: TaxonomyEnum;
        PostFormat: TaxonomyEnum;
    };
}
