/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The content for the object.
 */
export interface CommentContent {
    /**
     * Content for the object, as it exists in the database.
     */
    raw?: string;
    /**
     * HTML content for the object, transformed for display.
     */
    rendered?: string;
}
export interface CommentContentOpt {
    /**
     * Content for the object, as it exists in the database.
     */
    raw?: string;
    /**
     * HTML content for the object, transformed for display.
     */
    rendered?: string;
}
