/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorData } from './errorData';
export interface Error {
    code?: string;
    message?: string;
    data?: ErrorData;
}
export interface ErrorOpt {
    code?: string;
    message?: string;
    data?: ErrorData;
}
