/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostContent } from './postContent';
import { PostExcerpt } from './postExcerpt';
import { PostGuid } from './postGuid';
import { PostTitle } from './postTitle';
export interface PostRevision {
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    guid?: PostGuid;
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The date the object was last modified, in the site's timezone.
     */
    modified?: Date;
    /**
     * The date the object was last modified, as GMT.
     */
    modifiedGmt?: Date;
    /**
     * The ID for the parent of the object.
     */
    parent?: number;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    title?: PostTitle;
    content?: PostContent;
    excerpt?: PostExcerpt;
    /**
     * Preview link for the post.
     */
    previewLink?: string;
}
export interface PostRevisionOpt {
    /**
     * The ID for the author of the object.
     */
    author?: number;
    /**
     * The date the object was published, in the site's timezone.
     */
    date?: Date;
    /**
     * The date the object was published, as GMT.
     */
    dateGmt?: Date;
    guid?: PostGuid;
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The date the object was last modified, in the site's timezone.
     */
    modified?: Date;
    /**
     * The date the object was last modified, as GMT.
     */
    modifiedGmt?: Date;
    /**
     * The ID for the parent of the object.
     */
    parent?: number;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    slug?: string;
    title?: PostTitle;
    content?: PostContent;
    excerpt?: PostExcerpt;
    /**
     * Preview link for the post.
     */
    previewLink?: string;
}
