/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface SearchResult {
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * URL to the object.
     */
    url?: string;
    /**
     * Object type.
     */
    type?: SearchResult.TypeEnum;
    /**
     * Object subtype.
     */
    subtype?: SearchResult.SubtypeEnum;
}
export interface SearchResultOpt {
    /**
     * Unique identifier for the object.
     */
    id?: number;
    /**
     * The title for the object.
     */
    title?: string;
    /**
     * URL to the object.
     */
    url?: string;
    /**
     * Object type.
     */
    type?: SearchResult.TypeEnum;
    /**
     * Object subtype.
     */
    subtype?: SearchResult.SubtypeEnum;
}
export declare namespace SearchResult {
    type TypeEnum = 'post';
    const TypeEnum: {
        Post: "post";
    };
    type SubtypeEnum = 'post' | 'page';
    const SubtypeEnum: {
        Post: SubtypeEnum;
        Page: SubtypeEnum;
    };
}
