/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Status {
    /**
     * The title for the status.
     */
    name?: string;
    /**
     * Whether posts with this status should be private.
     */
    _private?: boolean;
    /**
     * Whether posts with this status should be protected.
     */
    _protected?: boolean;
    /**
     * Whether posts of this status should be shown in the front end of the site.
     */
    _public?: boolean;
    /**
     * Whether posts with this status should be publicly-queryable.
     */
    queryable?: boolean;
    /**
     * Whether to include posts in the edit listing for their post type.
     */
    showInList?: boolean;
    /**
     * An alphanumeric identifier for the status.
     */
    slug?: string;
}
export interface StatusOpt {
    /**
     * The title for the status.
     */
    name?: string;
    /**
     * Whether posts with this status should be private.
     */
    _private?: boolean;
    /**
     * Whether posts with this status should be protected.
     */
    _protected?: boolean;
    /**
     * Whether posts of this status should be shown in the front end of the site.
     */
    _public?: boolean;
    /**
     * Whether posts with this status should be publicly-queryable.
     */
    queryable?: boolean;
    /**
     * Whether to include posts in the edit listing for their post type.
     */
    showInList?: boolean;
    /**
     * An alphanumeric identifier for the status.
     */
    slug?: string;
}
