"use strict";
/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Tag;
(function (Tag) {
    Tag.TaxonomyEnum = {
        Category: 'category',
        PostTag: 'post_tag',
        NavMenu: 'nav_menu',
        LinkCategory: 'link_category',
        PostFormat: 'post_format'
    };
})(Tag = exports.Tag || (exports.Tag = {}));
