/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The visibility settings for the taxonomy.
 */
export interface TaxonomyVisibility {
    /**
     * Whether a taxonomy is intended for use publicly either via the admin interface or by front-end users.
     */
    _public?: boolean;
    /**
     * Whether the taxonomy is publicly queryable.
     */
    publiclyQueryable?: boolean;
    /**
     * Whether to generate a default UI for managing this taxonomy.
     */
    showUi?: boolean;
    /**
     * Whether to allow automatic creation of taxonomy columns on associated post-types table.
     */
    showAdminColumn?: boolean;
    /**
     * Whether to make the taxonomy available for selection in navigation menus.
     */
    showInNavMenus?: boolean;
    /**
     * Whether to show the taxonomy in the quick/bulk edit panel.
     */
    showInQuickEdit?: boolean;
}
export interface TaxonomyVisibilityOpt {
    /**
     * Whether a taxonomy is intended for use publicly either via the admin interface or by front-end users.
     */
    _public?: boolean;
    /**
     * Whether the taxonomy is publicly queryable.
     */
    publiclyQueryable?: boolean;
    /**
     * Whether to generate a default UI for managing this taxonomy.
     */
    showUi?: boolean;
    /**
     * Whether to allow automatic creation of taxonomy columns on associated post-types table.
     */
    showAdminColumn?: boolean;
    /**
     * Whether to make the taxonomy available for selection in navigation menus.
     */
    showInNavMenus?: boolean;
    /**
     * Whether to show the taxonomy in the quick/bulk edit panel.
     */
    showInQuickEdit?: boolean;
}
