/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaxonomyVisibility } from './taxonomyVisibility';
export interface Taxonomy {
    /**
     * All capabilities used by the taxonomy.
     */
    capabilities?: any;
    /**
     * A human-readable description of the taxonomy.
     */
    description?: string;
    /**
     * Whether or not the taxonomy should have children.
     */
    hierarchical?: boolean;
    /**
     * Human-readable labels for the taxonomy for various contexts.
     */
    labels?: any;
    /**
     * The title for the taxonomy.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the taxonomy.
     */
    slug?: string;
    /**
     * Whether or not the term cloud should be displayed.
     */
    showCloud?: boolean;
    /**
     * Types associated with the taxonomy.
     */
    types?: Array<string>;
    /**
     * REST base route for the taxonomy.
     */
    restBase?: string;
    visibility?: TaxonomyVisibility;
}
export interface TaxonomyOpt {
    /**
     * All capabilities used by the taxonomy.
     */
    capabilities?: any;
    /**
     * A human-readable description of the taxonomy.
     */
    description?: string;
    /**
     * Whether or not the taxonomy should have children.
     */
    hierarchical?: boolean;
    /**
     * Human-readable labels for the taxonomy for various contexts.
     */
    labels?: any;
    /**
     * The title for the taxonomy.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the taxonomy.
     */
    slug?: string;
    /**
     * Whether or not the term cloud should be displayed.
     */
    showCloud?: boolean;
    /**
     * Types associated with the taxonomy.
     */
    types?: Array<string>;
    /**
     * REST base route for the taxonomy.
     */
    restBase?: string;
    visibility?: TaxonomyVisibility;
}
