/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Type {
    /**
     * All capabilities used by the post type.
     */
    capabilities?: any;
    /**
     * A human-readable description of the post type.
     */
    description?: string;
    /**
     * Whether or not the post type should have children.
     */
    hierarchical?: boolean;
    /**
     * Whether or not the post type can be viewed.
     */
    viewable?: boolean;
    /**
     * Human-readable labels for the post type for various contexts.
     */
    labels?: any;
    /**
     * The title for the post type.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the post type.
     */
    slug?: string;
    /**
     * All features, supported by the post type.
     */
    supports?: any;
    /**
     * Taxonomies associated with post type.
     */
    taxonomies?: Array<string>;
    /**
     * REST base route for the post type.
     */
    restBase?: string;
}
export interface TypeOpt {
    /**
     * All capabilities used by the post type.
     */
    capabilities?: any;
    /**
     * A human-readable description of the post type.
     */
    description?: string;
    /**
     * Whether or not the post type should have children.
     */
    hierarchical?: boolean;
    /**
     * Whether or not the post type can be viewed.
     */
    viewable?: boolean;
    /**
     * Human-readable labels for the post type for various contexts.
     */
    labels?: any;
    /**
     * The title for the post type.
     */
    name?: string;
    /**
     * An alphanumeric identifier for the post type.
     */
    slug?: string;
    /**
     * All features, supported by the post type.
     */
    supports?: any;
    /**
     * Taxonomies associated with post type.
     */
    taxonomies?: Array<string>;
    /**
     * REST base route for the post type.
     */
    restBase?: string;
}
