/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Avatar URLs for the user.
 */
export interface UserAvatarUrls {
    /**
     * Avatar URL with image size of 24 pixels.
     */
    _24?: string;
    /**
     * Avatar URL with image size of 48 pixels.
     */
    _48?: string;
    /**
     * Avatar URL with image size of 96 pixels.
     */
    _96?: string;
}
export interface UserAvatarUrlsOpt {
    /**
     * Avatar URL with image size of 24 pixels.
     */
    _24?: string;
    /**
     * Avatar URL with image size of 48 pixels.
     */
    _48?: string;
    /**
     * Avatar URL with image size of 96 pixels.
     */
    _96?: string;
}
