/**
 * localhost:1234
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The content for the object.
 */
export interface WpBlockContent {
    /**
     * Content for the object, as it exists in the database.
     */
    raw?: string;
    /**
     * Version of the content block format used by the object.
     */
    blockVersion?: number;
    /**
     * Whether the content is protected with a password.
     */
    _protected?: boolean;
}
export interface WpBlockContentOpt {
    /**
     * Content for the object, as it exists in the database.
     */
    raw?: string;
    /**
     * Version of the content block format used by the object.
     */
    blockVersion?: number;
    /**
     * Whether the content is protected with a password.
     */
    _protected?: boolean;
}
